### ISSUE TITLE
Sidebar menu not appear

### ISSUE THREAD

**Issue by elfarqy** [haqqi/yii2-chopper-admin-template#1]
I want to create several dynamic menus in sidebar. Then, i create sidebar-menu.php with null `items` in config like this 
```
[
    'icon'  => FA::icon('users'),
    'label' => 'Users',
    'items' => []
  ],
```
But i can't see this menu in sidebar. But, when i deleted the `items`  from the menu config, that item suddenly appear.

**Comment by haqqi** [comment]
This is not a bug. You can set `hideEmptyItems` to `false` when initializing the widget.

**Comment by haqqi** [comment]
Why do you even set items if it is empty?
